apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-app
  namespace: metrics-app
  labels:
    app: metrics-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-app
  template:
    metadata:
      labels:
        app: metrics-app
        vcluster-tenant: tenant1
    spec:
      nodeName: edge-node-external
      containers:
        - name: metrics-app
          image: mariorgl/cndro26-metrics:amd64
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
          resources:
            limits:
              cpu: "0.5"
              memory: "128Mi"
            requests:
              cpu: "0.25"
              memory: "64Mi"
