apiVersion: v1
kind: Service
metadata:
  name: metrics-app
  namespace: metrics-app
  annotations:
    service.cilium.io/global: "false"
spec:
  selector:
    app: metrics-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP