apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-scraper
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: platform/kubernetes/scraper
    repoURL: https://github.com/mario26rgl/cndro26-vcluster-cilium-poc
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions: []
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-app
spec:
  project: tenant-one
  source:
    repoURL: https://github.com/mario26rgl/cndro26-vcluster-cilium-poc
    path: platform/kubernetes/metrics
    targetRevision: HEAD
  destination:
    server: https://tenant-one.tenant-one
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s