{{- if .Values.healthcheck.enabled }}
{{- $vclusterNamespace := .Values.vcluster_config.namespace -}}
{{- $vclusterName := .Values.vcluster_config.name -}}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-kubelet-health-checks
  namespace: {{ $vclusterNamespace }}
spec:
  endpointSelector:
    matchLabels:
      vcluster.loft.sh/managed-by: {{ $vclusterName }}
  ingress:
  - fromCIDR:
    - 10.0.0.0/16  # Node subnet (kubelet IP)
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      rules:
        http:
        - method: 'GET'
          path: '/health'
{{- end }}