apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-scraper
  namespace: platform-observability
  labels:
    app: platform-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-scraper
  template:
    metadata:
      labels:
        app: platform-scraper
    spec:
      containers:
        - name: scraper
          image: curlimages/curl:8.7.1
          resources:
            limits:
              cpu: "0.5"
              memory: "128Mi"
            requests:
              cpu: "0.25"
              memory: "64Mi"
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                echo "Scraping /metrics..."
                curl -sS http://{{ .Values.appName }}-x-{{ .Values.appNamespace }}-x-{{ .Values.vclusterName }}.{{ .Values.vclusterNamespace }}:80/metrics || echo "FAIL";
                sleep 5;
              done